version: '3.7'
services:

  postgres:
      container_name: postgres_container
      build: ./postgre
      image: postgres
      restart: always
      env_file:
        - .env
      ports: 
            - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
